services:
  - type: web
    name: thetamind-landing
    env: node
    region: oregon
    plan: free
    rootDir: landing
    buildCommand: npm ci && npm run build
    startCommand: npm start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: NEXT_TELEMETRY_DISABLED
        value: "1" 